import { prisma } from '../../config/database';
import { ConflictStrategy } from '@prisma/client';

interface SyncConfiguration {
  id: string;
  userId: string;
  name: string;
  sourceConnectionId: string;
  targetConnectionId: string;
  direction: string;
  mode: string;
  conflictStrategy: ConflictStrategy;
  includeTables: string[];
  excludeTables: string[];
  cronExpression: string | null;
  batchSize: number;
  parallelTables: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

interface ChangeLog {
  id: string;
  syncConfigId: string;
  tableName: string;
  operation: string;
  primaryKeyValues: any;
  changeData: any;
  timestamp: Date;
  checkpoint: string;
  origin: string;
  synchronized: boolean;
  synchronizedAt: Date | null;
}

interface Conflict {
  id: string;
  syncConfigId: string;
  tableName: string;
  primaryKeyValues: any;
  sourceData: any;
  targetData: any;
  sourceTimestamp: Date;
  targetTimestamp: Date;
  strategy: ConflictStrategy;
  resolution: string | null;
  resolvedData: any;
  resolved: boolean;
  resolvedAt: Date | null;
  resolvedBy: string | null;
  createdAt: Date;
}

interface ResolvedConflict {
  conflictId: string;
  resolution: 'source' | 'target' | 'manual';
  resolvedData: any;
}

/**
 * ConflictResolverService - Handles conflict detection and resolution for bidirectional sync
 * 
 * Implements multiple conflict resolution strategies:
 * - Last_Write_Wins: Compare timestamps and keep most recent
 * - Source_Wins: Always prefer source database changes
 * - Target_Wins: Always prefer target database changes
 * - Manual_Resolution: Create conflict record and pause sync for affected records
 * 
 * Requirements: 3.5, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8
 */
export class ConflictResolverService {
  /**
   * Detect conflicts by comparing source and target change logs
   * 
   * A conflict occurs when the same record (identified by primary key values)
   * has been modified in both source and target databases between sync cycles.
   * 
   * Requirements: 3.5
   */
  async detectConflicts(
    sourceLogs: ChangeLog[],
    targetLogs: ChangeLog[]
  ): Promise<Conflict[]> {
    const conflicts: Conflict[] = [];

    // Create a map of target changes by table and primary key for efficient lookup
    const targetChangeMap = new Map<string, ChangeLog>();
    
    for (const targetLog of targetLogs) {
      const key = this.createChangeKey(targetLog.tableName, targetLog.primaryKeyValues);
      targetChangeMap.set(key, targetLog);
    }

    // Check each source change for conflicts with target changes
    for (const sourceLog of sourceLogs) {
      const key = this.createChangeKey(sourceLog.tableName, sourceLog.primaryKeyValues);
      const targetLog = targetChangeMap.get(key);

      if (targetLog) {
        // Conflict detected: same record modified in both databases
        const conflict: Conflict = {
          id: '', // Will be generated by Prisma
          syncConfigId: sourceLog.syncConfigId,
          tableName: sourceLog.tableName,
          primaryKeyValues: sourceLog.primaryKeyValues,
          sourceData: sourceLog.changeData,
          targetData: targetLog.changeData,
          sourceTimestamp: sourceLog.timestamp,
          targetTimestamp: targetLog.timestamp,
          strategy: ConflictStrategy.LAST_WRITE_WINS, // Will be overridden by actual strategy
          resolution: null,
          resolvedData: null,
          resolved: false,
          resolvedAt: null,
          resolvedBy: null,
          createdAt: new Date(),
        };

        conflicts.push(conflict);
      }
    }

    return conflicts;
  }

  /**
   * Create a unique key for a change log entry based on table name and primary key values
   */
  private createChangeKey(tableName: string, primaryKeyValues: any): string {
    // Sort keys to ensure consistent ordering
    const sortedKeys = Object.keys(primaryKeyValues).sort();
    const keyParts = sortedKeys.map(k => `${k}:${primaryKeyValues[k]}`);
    return `${tableName}:${keyParts.join(',')}`;
  }

  /**
   * Resolve a conflict using the specified strategy
   * 
   * Requirements: 4.1, 4.2, 4.3, 4.4, 4.5
   */
  async resolveConflict(
    conflict: Conflict,
    strategy: ConflictStrategy
  ): Promise<ResolvedConflict> {
    let resolution: 'source' | 'target' | 'manual';
    let resolvedData: any;

    switch (strategy) {
      case ConflictStrategy.LAST_WRITE_WINS:
        // Compare timestamps and keep the most recent version
        if (conflict.sourceTimestamp >= conflict.targetTimestamp) {
          resolution = 'source';
          resolvedData = conflict.sourceData;
        } else {
          resolution = 'target';
          resolvedData = conflict.targetData;
        }
        break;

      case ConflictStrategy.SOURCE_WINS:
        // Always use source database version
        resolution = 'source';
        resolvedData = conflict.sourceData;
        break;

      case ConflictStrategy.TARGET_WINS:
        // Always use target database version
        resolution = 'target';
        resolvedData = conflict.targetData;
        break;

      case ConflictStrategy.MANUAL_RESOLUTION:
        // Create conflict record and pause sync for this record
        // The conflict will remain unresolved until manual intervention
        resolution = 'manual';
        resolvedData = null;
        
        // Store the conflict in the database for manual resolution
        const storedConflict = await prisma.conflict.create({
          data: {
            syncConfigId: conflict.syncConfigId,
            tableName: conflict.tableName,
            primaryKeyValues: conflict.primaryKeyValues,
            sourceData: conflict.sourceData,
            targetData: conflict.targetData,
            sourceTimestamp: conflict.sourceTimestamp,
            targetTimestamp: conflict.targetTimestamp,
            strategy: ConflictStrategy.MANUAL_RESOLUTION,
            resolved: false,
          },
        });

        return {
          conflictId: storedConflict.id,
          resolution: 'manual',
          resolvedData: null,
        };

      default:
        throw new Error(`Unknown conflict strategy: ${strategy}`);
    }

    // For automatic resolution strategies, store the resolved conflict
    const storedConflict = await prisma.conflict.create({
      data: {
        syncConfigId: conflict.syncConfigId,
        tableName: conflict.tableName,
        primaryKeyValues: conflict.primaryKeyValues,
        sourceData: conflict.sourceData,
        targetData: conflict.targetData,
        sourceTimestamp: conflict.sourceTimestamp,
        targetTimestamp: conflict.targetTimestamp,
        strategy,
        resolution,
        resolvedData,
        resolved: true,
        resolvedAt: new Date(),
      },
    });

    return {
      conflictId: storedConflict.id,
      resolution,
      resolvedData,
    };
  }

  /**
   * Manually resolve a conflict with user-provided resolution data
   * 
   * Requirements: 4.8
   */
  async resolveConflictManually(
    conflictId: string,
    resolution: any,
    userId: string
  ): Promise<void> {
    // Verify the conflict exists and is unresolved
    const conflict = await prisma.conflict.findUnique({
      where: { id: conflictId },
    });

    if (!conflict) {
      throw new Error(`Conflict ${conflictId} not found`);
    }

    if (conflict.resolved) {
      throw new Error(`Conflict ${conflictId} is already resolved`);
    }

    // Update the conflict with the manual resolution
    await prisma.conflict.update({
      where: { id: conflictId },
      data: {
        resolution: 'manual',
        resolvedData: resolution,
        resolved: true,
        resolvedAt: new Date(),
        resolvedBy: userId,
      },
    });
  }

  /**
   * Get all unresolved conflicts for a sync configuration
   * 
   * Requirements: 4.7
   */
  async getUnresolvedConflicts(configId: string): Promise<Conflict[]> {
    const conflicts = await prisma.conflict.findMany({
      where: {
        syncConfigId: configId,
        resolved: false,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });

    return conflicts as Conflict[];
  }

  /**
   * Get conflict history for a sync configuration
   * 
   * Requirements: 4.6
   */
  async getConflictHistory(configId: string, limit: number = 100): Promise<Conflict[]> {
    const conflicts = await prisma.conflict.findMany({
      where: {
        syncConfigId: configId,
      },
      orderBy: {
        createdAt: 'desc',
      },
      take: limit,
    });

    return conflicts as Conflict[];
  }
}
